name: feature-development

on:
  push:
    branches:
      - "feature/*"

jobs:
  install_dependencies:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install pnpm
        run: |
          curl -L https://unpkg.com/@pnpm/self-installer | node

      - name: Install dependencies
        run: |
          pnpm install

  build:
    needs: install_dependencies
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build
        run: |
          cd packages/token
          pnpm build

  commit:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Commit
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git diff --quiet && git diff --staged --quiet || (git add . && git commit -m "[CI] build: build token")

      # push changes
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
