name: feature-development

on:
  push:
    branches:
      - "feature/*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install pnpm
        run: |
          curl -L https://unpkg.com/@pnpm/self-installer | node

      - name: Install dependencies
        run: |
          pnpm install

      - name: Build
        run: |
          cd packages/token
          pnpm build

      - name: Commit
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "[CI] build: build token"

      # push changes
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
